import { useLanguage } from '../../context/LanguageContext';
import { translations } from '../../i18n/translations';

// Comprehensive Hindi translation dictionary covering all components, pages,
// roles, statuses, and data labels.
export const extraHi = {
  // University Admin New Problems & Workflow
  "New Problems": "नई समस्याएं",
  "New Problems for Your University": "आपके विश्वविद्यालय के लिए नई समस्याएं",
  "Review challenges routed to your university by AI matching or government recommendation. Approve to assign faculty mentors or reject with reasons.": "AI मिलान या सरकारी सिफारिश द्वारा आपके विश्वविद्यालय को भेजी गई चुनौतियों की समीक्षा करें। फैकल्टी मेंटर्स नियुक्त करने के लिए स्वीकृत करें या कारण सहित अस्वीकार करें।",
  "Approve": "स्वीकृत करें",
  "Reject": "अस्वीकार करें",
  "Rejection Reason": "अस्वीकृति का कारण",
  "Assign Faculty Mentors": "फैकल्टी मेंटर्स नियुक्त करें",
  "Assign Faculty": "फैकल्टी नियुक्त करें",
  "Assign Faculty Mentor(s)": "फैकल्टी मेंटर्स नियुक्त करें",
  "Confirm & Assign Faculty": "पुष्टि करें एवं फैकल्टी नियुक्त करें",
  "Primary Faculty Mentor": "प्राथमिक फैकल्टी मेंटर",
  "Co-Mentor": "सह-मेंटर",
  "Co-Mentors": "सह-मेंटर",
  "Selected Faculty": "चयनित फैकल्टी",
  "Available Faculty Members": "उपलब्ध फैकल्टी सदस्य",
  "Faculty ID": "फैकल्टी आईडी",
  "Faculty Name": "फैकल्टी का नाम",
  "Select Faculty": "फैकल्टी चुनें",
  "Confirm Faculty Assignment": "फैकल्टी आवंटन की पुष्टि करें",
  "MOU": "एमओयू (MOU)",
  "Memorandum of Understanding (MOU)": "सहमति पत्र (MOU)",
  "Official collaboration agreements and partnerships between your university, industries, and government.": "आपके विश्वविद्यालय, उद्योगों और सरकार के बीच आधिकारिक सहयोग समझौते और साझेदारियां।",
  "Past Projects": "पूर्व परियोजनाएं",
  "Archived record of all successfully solved and deployed challenges by your university.": "आपके विश्वविद्यालय द्वारा सफलतापूर्वक हल और तैनात की गई सभी चुनौतियों का संग्रहीत रिकॉर्ड।",
  "Industry Partner": "उद्योग भागीदार",
  "Industry Mentor": "उद्योग मेंटर",
  "Industry Mentor / SPOC": "उद्योग मेंटर / एसपीओसी",
  "No New Problems": "कोई नई समस्या नहीं",
  "No Past Projects": "कोई पूर्व परियोजना नहीं",
  "No MOU Available": "कोई एमओयू उपलब्ध नहीं है",
  "Document Pending / Not Uploaded": "दस्तावेज़ लंबित / अपलोड नहीं हुआ",
  "View & Download Document": "दस्तावेज़ देखें और डाउनलोड करें",
  "Download MOU / Document": "एमओयू / दस्तावेज़ डाउनलोड करें",
  "Completed & Deployed": "पूर्ण एवं तैनात",
  "Primary Mentor": "प्राथमिक मेंटर",
  "Student Team": "छात्र टीम",
  "Match Score": "मैच स्कोर",
  "Priority Rank": "प्राथमिकता रैंक",
  "AI Category": "एआई श्रेणी",
  "AI Severity": "एआई गंभीरता",
  "AI Priority": "एआई प्राथमिकता",
  "Match Rationale": "मैच का औचित्य",
  "Submitter / Source": "प्रस्तुतकर्ता / स्रोत",
  "Reject Problem": "समस्या अस्वीकार करें",
  "Please provide a detailed reason for rejecting this challenge recommendation. This will be shared with the Government and problem submitters.": "कृपया इस चुनौती सिफारिश को अस्वीकार करने का विस्तृत कारण बताएं। यह सरकार और समस्या प्रस्तुतकर्ताओं के साथ साझा किया जाएगा।",
  "Enter rejection reason (required)...": "अस्वीकृति का कारण दर्ज करें (अनिवार्य)...",
  "Confirm Rejection": "अस्वीकृति की पुष्टि करें",
  "Rejecting...": "अस्वीकार किया जा रहा है...",
  "Assigning...": "नियुक्त किया जा रहा है...",
  "Approving...": "स्वीकृत किया जा रहा है...",
  "No faculty members found for your university.": "आपके विश्वविद्यालय के लिए कोई फैकल्टी सदस्य नहीं मिले।",
  "Search past projects by title, domain, industry, faculty, or student...": "शीर्षक, डोमेन, उद्योग, फैकल्टी, या छात्र द्वारा पूर्व परियोजनाएं खोजें...",
  "Search MOUs by company, domain, or project...": "कंपनी, डोमेन, या प्रोजेक्ट द्वारा एमओयू खोजें...",
  "Review New Problems": "नई समस्याओं की समीक्षा करें",
  "Review problem statements sent to your university and Approve or Reject them.": "अपने विश्वविद्यालय को भेजी गई समस्या विवरणों की समीक्षा करें और उन्हें स्वीकृत या अस्वीकार करें।",
  "Go to New Problems": "नई समस्याओं पर जाएं",
  "Go to MOU": "एमओयू पर जाएं",
  "Go to Past Projects": "पूर्व परियोजनाओं पर जाएं",
  "Review official tripartite collaboration agreements and industry partnerships.": "आधिकारिक त्रिपक्षीय सहयोग समझौतों और उद्योग साझेदारियों की समीक्षा करें।",
  "View archived record of all successfully solved and deployed challenges.": "सफलतापूर्वक हल और तैनात की गई सभी चुनौतियों का संग्रहीत रिकॉर्ड देखें।",

  // Required skills / technologies chips
  "Required Skills:": "आवश्यक कौशल:",
  "Required Skills": "आवश्यक कौशल",

  // Milestones (Government project tracking)
  "Project Milestones": "प्रोजेक्ट माइलस्टोन",
  "Complete": "पूर्ण",
  "Problem Submitted": "समस्या प्रस्तुत की गई",
  "Routed to Universities": "विश्वविद्यालयों को भेजा गया",
  "University Allocated": "विश्वविद्यालय आवंटित",
  "Faculty Assigned": "फैकल्टी नियुक्त",
  "Student Team Formed": "छात्र टीम गठित",
  "Development In Progress": "विकास कार्य जारी",
  "Solution Deployed": "समाधान तैनात",
  "View Milestones": "माइलस्टोन देखें",
  "Hide Milestones": "माइलस्टोन छुपाएं",
  "No data available yet.": "अभी कोई डेटा उपलब्ध नहीं है।",
  "Total": "कुल",

  // Student portal & Certificate workflow
  "Ongoing Problems in University": "विश्वविद्यालय में चल रही समस्याएं",
  "New Projects": "नए प्रोजेक्ट्स",
  "My Project": "मेरा प्रोजेक्ट",
  "Faculty Mentoring:": "मार्गदर्शक फैकल्टी:",
  "Faculty Mentoring": "मार्गदर्शक फैकल्टी",
  "Skills Required:": "आवश्यक कौशल:",
  "Skills Required": "आवश्यक कौशल",
  "Industry Name:": "उद्योग का नाम:",
  "Student Names Working on It:": "कार्यरत छात्रों के नाम:",
  "Team selection in progress": "टीम चयन प्रगति पर है",
  "All Projects": "सभी प्रोजेक्ट्स",
  "Ongoing Work": "चल रहा कार्य",
  "Solved & Completed Work": "हल एवं पूर्ण कार्य",
  "E-Certificate Portal": "ई-प्रमाणपत्र पोर्टल",
  "Certificate Locked (In Progress)": "प्रमाणपत्र लॉक है (प्रगति पर)",
  "Certificate is not yet available for this problem": "इस समस्या के लिए प्रमाणपत्र अभी उपलब्ध नहीं है",
  "A certificate will only be issued once the project reaches the final 'Solution Deployed' milestone.": "प्रमाणपत्र केवल तभी जारी किया जाएगा जब परियोजना अंतिम 'समाधान तैनात' चरण तक पहुंच जाएगी।",
  "Eligible & Verified": "पात्र एवं सत्यापित",
  "Download Certificate (PDF / Print)": "प्रमाणपत्र डाउनलोड करें (PDF / प्रिंट)",
  "CERTIFICATE OF EXCELLENCE": "उत्कृष्टता प्रमाणपत्र",
  "Problem:": "समस्या:",
  "Project Associated": "संबद्ध परियोजना",
  "Please select an approved university.": "कृपया एक अनुमोदित विश्वविद्यालय चुनें।",
  "No ongoing approved problems found for your university at this time.": "इस समय आपके विश्वविद्यालय के लिए कोई स्वीकृत चल रही समस्या नहीं मिली।",
  "Loading ongoing university problems...": "विश्वविद्यालय की चल रही समस्याएं लोड हो रही हैं...",
  "Loading your project memberships...": "आपकी प्रोजेक्ट सदस्यता लोड हो रही है...",
  "Verifying certificate eligibility...": "प्रमाणपत्र पात्रता सत्यापित की जा रही है...",
  "No Project Certificates Found": "कोई प्रोजेक्ट प्रमाणपत्र नहीं मिला",

  // Dashboard charts
  "Lifecycle Status Breakdown": "जीवनचक्र स्थिति विश्लेषण",
  "Incoming Problem Status": "आने वाली समस्याओं की स्थिति",
  "Allocated Problems by Domain": "डोमेन अनुसार आवंटित समस्याएं",
  "Proposal Status Breakdown": "प्रस्ताव स्थिति विश्लेषण",
  "Relevant Projects by Domain": "डोमेन अनुसार प्रासंगिक प्रोजेक्ट्स",
  "Awaiting Our Decision": "हमारे निर्णय की प्रतीक्षा",
  "Rejected by Us": "हमारे द्वारा अस्वीकृत",
  "Industry Submitted": "उद्योग द्वारा प्रस्तुत",

  // Attachments / applications
  "Attach Supporting PDF (optional)": "सहायक PDF संलग्न करें (वैकल्पिक)",
  "Drag & drop a PDF here, or click to browse": "PDF यहां खींचें और छोड़ें, या ब्राउज़ करने हेतु क्लिक करें",
  "Attached Document:": "संलग्न दस्तावेज़:",
  "GitHub": "गिटहब",

  // Actions & Buttons
  "Accept": "स्वीकार करें",
  "Accepted": "स्वीकृत",
  "Accepted by Us": "हमारे द्वारा स्वीकृत",
  "Accepted by a University": "विश्वविद्यालय द्वारा स्वीकृत",
  "Active Problems": "सक्रिय समस्याएं",
  "Active Project — In Progress": "सक्रिय प्रोजेक्ट — प्रगति पर",
  "Active Projects": "सक्रिय प्रोजेक्ट्स",
  "Additional detail:": "अतिरिक्त विवरण:",
  "All": "सभी",
  "All Domains": "सभी डोमेन",
  "All Statuses": "सभी स्थितियां",
  "All Universities": "सभी विश्वविद्यालय",
  "Allocate Faculty": "फैकल्टी आवंटित करें",
  "Allocate to Faculty": "फैकल्टी को आवंटित करें",
  "Allocated": "आवंटित",
  "Allocated to Us": "हमें आवंटित",
  "Allocation Monitoring": "आवंटन निगरानी",
  "Allotted to You": "आपको आवंटित",
  "Already Decided": "पहले से निर्णयित",
  "Assigned Faculties": "आवंटित फैकल्टी",
  "Assigned Problems & Students": "आवंटित समस्याएं एवं छात्र",
  "Avg. Resolution Time": "औसत समाधान समय",
  "Awaiting Allocation": "आवंटन की प्रतीक्षा",
  "Awaiting University Allocation": "विश्वविद्यालय आवंटन की प्रतीक्षा",
  "Back to Projects": "प्रोजेक्ट्स पर वापस जाएं",
  "Before your problem is routed to Government and University Administration, let's check whether a solution already exists.": "आपकी समस्या को सरकार और विश्वविद्यालय प्रशासन के पास भेजने से पहले, जांचें कि क्या इसका कोई समाधान पहले से मौजूद है।",
  "Browse top-performing students and reach out for opportunities.": "शीर्ष प्रदर्शन करने वाले छात्रों को देखें और अवसरों के लिए संपर्क करें।",
  "Cancel": "रद्द करें",
  "Citizen Votes:": "नागरिक वोट:",
  "Collaboration Opportunities": "सहयोग के अवसर",
  "Collaboration Proposals": "सहयोग प्रस्ताव",
  "Common Reasons": "सामान्य कारण",
  "Confirmed Team": "पुष्ट टीम",
  "Continue": "जारी रखें",
  "Continue to My Problems": "मेरी समस्याओं पर जाएं",
  "Currently Active": "वर्तमान में सक्रिय",
  "Currently Being Solved": "वर्तमान में समाधानाधीन",
  "Deadline Completed": "समय सीमा पूर्ण",
  "Deadline for final allocation": "अंतिम आवंटन की समय सीमा",
  "Domain": "डोमेन",
  "Domain / Skills": "डोमेन / कौशल",
  "Domain:": "डोमेन:",
  "Edit Profile": "प्रोफ़ाइल संपादित करें",
  "Email": "ईमेल",
  "Email is required.": "ईमेल आवश्यक है।",
  "Estimated from solved problems": "समाधान की गई समस्याओं के आधार पर अनुमानित",
  "Existing Solutions in Your Area": "आपके क्षेत्र में मौजूदा समाधान",
  "Expected Role of Industry": "उद्योग की अपेक्षित भूमिका",
  "Explain why and continue": "कारण बताएं और जारी रखें",
  "Explain your problem (optional but recommended)": "अपनी समस्या बताएं (वैकल्पिक लेकिन अनुशंसित)",
  "Faculty": "फैकल्टी",
  "Faculty:": "फैकल्टी:",
  "Final allocation deadline": "अंतिम आवंटन की समय सीमा",
  "Go to Allocations": "आवंटन पर जाएं",
  "Go to Incoming Problems": "आने वाली समस्याओं पर जाएं",
  "Go to Leaderboard": "लीडरबोर्ड पर जाएं",
  "Government Dashboard": "सरकार डैशबोर्ड",
  "Great — this existing solution has been noted as a match for your problem.": "बहुत अच्छा — इस मौजूदा समाधान को आपकी समस्या के लिए उपयुक्त माना गया है।",
  "History / Solved": "इतिहास / हल की गई",
  "Impact:": "प्रभाव:",
  "Improve My Explanation": "मेरा विवरण सुधारें",
  "Incoming Problem Statements": "प्राप्त समस्या विवरण",
  "Incoming from Government": "सरकार से प्राप्त",
  "Industry Collaboration Proposals": "उद्योग सहयोग प्रस्ताव",
  "Industry Employee Dashboard": "उद्योग कर्मचारी डैशबोर्ड",
  "In Progress": "प्रगति पर",
  "Involving Industry": "उद्योग शामिल",
  "Leaderboard": "लीडरबोर्ड",
  "Lifecycle analytics across all submitted problem statements.": "सभी प्रस्तुत समस्या विवरणों का जीवनचक्र विश्लेषण।",
  "Location:": "स्थान:",
  "Manage Allocations": "आवंटन प्रबंधित करें",
  "Managed Problems & Faculty Allocations": "प्रबंधित समस्याएं एवं फैकल्टी आवंटन",
  "Marked as a fit. You may request that Government consider implementing this existing solution in your area.": "इसे उपयुक्त माना गया है। आप सरकार से इस मौजूदा समाधान को अपने क्षेत्र में लागू करने पर विचार करने का अनुरोध कर सकते हैं।",
  "Microphone access was denied or is unavailable.": "माइक्रोफ़ोन की अनुमति अस्वीकार है या उपलब्ध नहीं है।",
  "Microphone permission was denied. Please allow microphone access and try again.": "माइक्रोफ़ोन की अनुमति अस्वीकार कर दी गई। कृपया माइक्रोफ़ोन की अनुमति दें और पुनः प्रयास करें।",
  "Monitor allocation priority/deadline status and allocate accepted problems to faculty.": "आवंटन की प्राथमिकता/समय सीमा की स्थिति देखें और स्वीकृत समस्याओं को फैकल्टी को आवंटित करें।",
  "Monitoring view. Accept/Reject decisions are now made by University Administration.": "निगरानी दृश्य। स्वीकार/अस्वीकार के निर्णय अब विश्वविद्यालय प्रशासन द्वारा किए जाते हैं।",
  "My Profile": "मेरी प्रोफ़ाइल",
  "Name": "नाम",
  "No accepted or rejected problems yet — review Incoming Problems first.": "अभी तक कोई स्वीकृत या अस्वीकृत समस्या नहीं है — पहले आने वाली समस्याओं की समीक्षा करें।",
  "No active collaborations yet.": "अभी तक कोई सक्रिय सहयोग नहीं है।",
  "No active projects allocated to your university yet.": "आपके विश्वविद्यालय को अभी तक कोई सक्रिय प्रोजेक्ट आवंटित नहीं किया गया है।",
  "No additional profile details on file yet.": "अभी तक कोई अतिरिक्त प्रोफ़ाइल विवरण उपलब्ध नहीं है।",
  "No assigned problems yet.": "अभी तक कोई समस्या आवंटित नहीं है।",
  "No closely matching existing solution was found. Your problem will proceed to Government and University Administration for review.": "कोई निकटतम मौजूदा समाधान नहीं मिला। आपकी समस्या समीक्षा के लिए सरकार और विश्वविद्यालय प्रशासन के पास भेजी जाएगी।",
  "No faculty allocations yet.": "अभी तक कोई फैकल्टी आवंटन नहीं है।",
  "No managed problems yet.": "अभी तक कोई प्रबंधित समस्या नहीं है।",
  "None of these a fit?": "इनमें से कोई भी उपयुक्त नहीं है?",
  "No problems found": "कोई समस्या नहीं मिली।",
  "No problems in this view right now.": "इस दृश्य में अभी कोई समस्या नहीं है।",
  "No problems match this filter.": "इस फ़िल्टर से कोई समस्या मेल नहीं खाती।",
  "No problems submitted yet.": "अभी तक कोई समस्या प्रस्तुत नहीं की गई है।",
  "No projects are available for your university right now.": "आपके विश्वविद्यालय के लिए अभी कोई प्रोजेक्ट उपलब्ध नहीं है।",
  "No proposals match these filters.": "इन फ़िल्टरों से कोई प्रस्ताव मेल नहीं खाता।",
  "No students currently assigned.": "वर्तमान में कोई छात्र आवंटित नहीं है।",
  "No successful projects yet.": "अभी तक कोई सफल प्रोजेक्ट नहीं है।",
  "No university allocations yet.": "अभी तक कोई विश्वविद्यालय आवंटन नहीं है।",
  "Not yet allocated": "अभी आवंटित नहीं",
  "Not yet assigned to a project.": "अभी तक किसी प्रोजेक्ट में आवंटित नहीं किया गया है।",
  "Our Response:": "हमारी प्रतिक्रिया:",
  "Password is required.": "पासवर्ड आवश्यक है।",
  "Pending Decision": "निर्णय लंबित",
  "Pending Review": "समीक्षा लंबित",
  "Please select a faculty member first.": "कृपया पहले एक फैकल्टी सदस्य चुनें।",
  "Please select at least one reason or describe your problem.": "कृपया कम से कम एक कारण चुनें या अपनी समस्या का विवरण दें।",
  "Problem": "समस्या",
  "Problem accepted.": "समस्या स्वीकृत।",
  "Problem Lifecycle Funnel": "समस्या जीवनचक्र फ़नल",
  "Problem Lifecycle Overview": "समस्या जीवनचक्र अवलोकन",
  "Problem not found.": "समस्या नहीं मिली।",
  "Problem rejected.": "समस्या अस्वीकृत।",
  "Problems by Domain": "डोमेन के अनुसार समस्याएं",
  "Problems by University": "विश्वविद्यालय के अनुसार समस्याएं",
  "Profile": "प्रोफ़ाइल",
  "Profile updated.": "प्रोफ़ाइल अपडेट की गई।",
  "Project": "प्रोजेक्ट",
  "Projects & Solved Problems": "प्रोजेक्ट्स एवं हल की गई समस्याएं",
  "Proposal accepted.": "प्रस्ताव स्वीकार कर लिया गया।",
  "Proposal rejected.": "प्रस्ताव अस्वीकार कर दिया गया।",
  "Proposals Pending Review": "समीक्षा हेतु लंबित प्रस्ताव",
  "Proposals submitted by universities for projects relevant to your industry.": "आपके उद्योग से संबंधित प्रोजेक्ट्स के लिए विश्वविद्यालयों द्वारा प्रस्तुत प्रस्ताव।",
  "Proposed Collaboration": "प्रस्तावित सहयोग",
  "Proposed Solution": "प्रस्तावित समाधान",
  "Proposed Solution Idea": "प्रस्तावित समाधान विचार",
  "Proposed Solution Idea:": "प्रस्तावित समाधान विचार:",
  "Reject": "अस्वीकार करें",
  "Rejected": "अस्वीकृत",
  "Relevant Projects": "प्रासंगिक प्रोजेक्ट्स",
  "Request Government Implementation": "सरकार से कार्यान्वयन का अनुरोध करें",
  "Request Implementation": "कार्यान्वयन का अनुरोध",
  "Required Expertise": "आवश्यक विशेषज्ञता",
  "Required Technologies": "आवश्यक तकनीकें",
  "Required Technologies:": "आवश्यक तकनीकें:",
  "Review Incoming Problems": "आने वाली समस्याओं की समीक्षा करें",
  "Review problem statements sent by Government and Accept or Reject them.": "सरकार द्वारा भेजे गए समस्या विवरणों की समीक्षा करें और उन्हें स्वीकार या अस्वीकार करें।",
  "Review proposals submitted by universities looking for industry partners.": "उद्योग साझेदारों की तलाश कर रहे विश्वविद्यालयों द्वारा प्रस्तुत प्रस्तावों की समीक्षा करें।",
  "SamadhanSetu v2.0 · Jharkhand": "समाधानसेतु v2.0 · झारखंड",
  "Save": "सहेजें",
  "Select…": "चुनें…",
  "Select faculty…": "फैकल्टी चुनें…",
  "Selected Reasons": "चयनित कारण",
  "Since an existing solution already fits your problem, you can request Government to consider implementing it in your area instead of starting a new project.": "चूंकि मौजूदा समाधान आपकी समस्या के लिए उपयुक्त है, आप नया प्रोजेक्ट शुरू करने के बजाय सरकार से इसे अपने क्षेत्र में लागू करने पर विचार करने का अनुरोध कर सकते हैं।",
  "Solved": "हल",
  "Status": "स्थिति",
  "Status Distribution by Source": "स्रोत के अनुसार स्थिति वितरण",
  "Student": "छात्र",
  "Students": "छात्र",
  "Students Participating": "भाग लेने वाले छात्र",
  "Students Solving Problems": "समस्याओं का समाधान कर रहे छात्र",
  "Students Working": "कार्यरत छात्र",
  "Students Working on This Problem": "इस समस्या पर कार्यरत छात्र",
  "Students Working:": "कार्यरत छात्र:",
  "Students:": "छात्र:",
  "Submit Reasons": "कारण प्रस्तुत करें",
  "Submitted": "प्रस्तुत",
  "Submitted:": "प्रस्तुत:",
  "Submitted On": "प्रस्तुत करने की तिथि",
  "Submitted Problems / Applications": "प्रस्तुत समस्याएं / आवेदन",
  "Suggested Industries:": "सुझाए गए उद्योग:",
  "Suggested Industry:": "सुझाया गया उद्योग:",
  "Technologies": "तकनीकें",
  "Technologies:": "तकनीकें:",
  "Technology": "तकनीक",
  "Tell Us Why the Existing Solution Doesn't Work": "बताएं कि मौजूदा समाधान काम क्यों नहीं करता",
  "This helps Government and University Administration understand why a new solution is needed.": "इससे सरकार और विश्वविद्यालय प्रशासन को समझने में मदद मिलेगी कि नए समाधान की आवश्यकता क्यों है।",
  "Total Proposals": "कुल प्रस्ताव",
  "Total Submitted": "कुल प्रस्तुत",
  "Total Submitted:": "कुल प्रस्तुत:",
  "Universities Engaged": "शामिल विश्वविद्यालय",
  "University": "विश्वविद्यालय",
  "University Active Project": "विश्वविद्यालय का सक्रिय प्रोजेक्ट",
  "University Administration Dashboard": "विश्वविद्यालय प्रशासन डैशबोर्ड",
  "University:": "विश्वविद्यालय:",
  "View Proposals": "प्रस्ताव देखें",
  "View collaboration proposals and connect with top students from the Leaderboard.": "सहयोग प्रस्ताव देखें और लीडरबोर्ड के शीर्ष छात्रों से जुड़ें।",
  "Voice Assistant": "वॉइस असिस्टेंट",
  "Voice Assistant unavailable": "वॉइस असिस्टेंट उपलब्ध नहीं है",
  "Welcome": "स्वागत है",
  "Your Submitted Problem": "आपकी प्रस्तुत समस्या",
  "Your Priority Rank:": "आपकी प्राथमिकता रैंक:",
  "Checking reason…": "कारण की समीक्षा की जा रही है…",
  "Your explanation looks genuine and sufficiently detailed. Your problem can now proceed to Government and University Administration.": "आपका विवरण प्रामाणिक एवं पर्याप्त विस्तृत प्रतीत होता है। आपकी समस्या अब सरकार और विश्वविद्यालय प्रशासन को समीक्षा के लिए भेजी जा सकती है।",
  "Your problem has been routed to Government and University Administration for review.": "आपकी समस्या समीक्षा के लिए सरकार और विश्वविद्यालय प्रशासन को भेज दी गई है।",

  // Role Badges & Stakeholder names
  "Citizen Portal": "नागरिक पोर्टल",
  "Student Portal": "छात्र पोर्टल",
  "Faculty Portal": "फैकल्टी पोर्टल",
  "University Administration Portal": "विश्वविद्यालय प्रशासन पोर्टल",
  "Government Portal": "सरकार पोर्टल",
  "Industry Employee Portal": "उद्योग कर्मचारी पोर्टल",
  "Citizen": "नागरिक",
  "University Administration": "विश्वविद्यालय प्रशासन",
  "Government": "सरकार",
  "Industry Employee": "उद्योग कर्मचारी",

  // Domains & Categories
  "Web Development": "वेब डेवलपमेंट",
  "Robotics": "रोबोटिक्स",
  "Agriculture": "कृषि",
  "Mechanical Design": "मैकेनिकल डिज़ाइन",
  "Healthcare": "स्वास्थ्य सेवा",
  "AI / Machine Learning": "एआई / मशीन लर्निंग",
  "IoT": "आईओटी",
  "Cybersecurity": "साइबर सुरक्षा",
  "Electronics": "इलेक्ट्रॉनिक्स",
  "Software Development": "सॉफ्टवेयर डेवलपमेंट",
  "Water & Sanitation": "जल एवं स्वच्छता",
  "Infrastructure": "बुनियादी ढांचा",
  "Environment": "पर्यावरण",
  "Education": "शिक्षा",
  "Civic Issue": "नागरिक समस्या",
  "General Civic": "सामान्य नागरिक",
  "Area Specific": "क्षेत्र विशेष",
  "City Specific": "शहर विशेष",
  "Statewide": "राज्यव्यापी",

  // Universities
  "BIT Mesra, Ranchi": "बीआईटी मेसरा, राँची",
  "BIT Mesra": "बीआईटी मेसरा",
  "NIT Jamshedpur": "एनआईटी जमशेदपुर",
  "IIT (ISM) Dhanbad": "आईआईटी (आईएसएम) धनबाद",
  "BAU Ranchi": "बीएयू राँची",

  // Common Problem Reasons
  "Existing solution is too expensive": "मौजूदा समाधान बहुत महंगा है",
  "Existing solution is not accessible": "मौजूदा समाधान सुलभ नहीं है",
  "Existing solution is not available in my area": "मौजूदा समाधान मेरे क्षेत्र में उपलब्ध नहीं है",
  "Existing solution is technically unsuitable": "मौजूदा समाधान तकनीकी रूप से अनुपयुक्त है",
  "Existing solution is difficult to use": "मौजूदा समाधान का उपयोग करना कठिन है",
  "Existing solution requires unavailable resources": "मौजूदा समाधान के लिए अनुपलब्ध संसाधनों की आवश्यकता है",
  "Existing solution is too slow": "मौजूदा समाधान बहुत धीमा है",
  "Existing solution is not scalable": "मौजूदा समाधान स्केलेबल नहीं है",
  "Existing solution does not solve the complete problem": "मौजूदा समाधान पूरी समस्या का समाधान नहीं करता",
  "Existing solution is outdated": "मौजूदा समाधान पुराना हो चुका है",
  "Other": "अन्य",

  // Form Fields & Profile keys
  "Department": "विभाग",
  "Student ID": "छात्र आईडी",
  "Student Id": "छात्र आईडी",
  "Semester / Year": "सेमेस्टर / वर्ष",
  "Semester": "सेमेस्टर",
  "Skills": "कौशल",
  "Skills:": "कौशल:",
  "Skills (comma separated)": "कौशल (अल्पविराम से अलग)",
  "Technologies (comma separated)": "तकनीकें (अल्पविराम से अलग)",
  "Faculty ID": "फैकल्टी आईडी",
  "Faculty Id": "फैकल्टी आईडी",
  "Expertise": "विशेषज्ञता",
  "Experience (years)": "अनुभव (वर्ष)",
  "Experience": "अनुभव",
  "Administration / Department": "प्रशासन / विभाग",
  "Designation": "पदनाम",
  "Administration ID": "प्रशासन आईडी",
  "Admin Id": "प्रशासन आईडी",
  "Address": "पता",
  "Website": "वेबसाइट",
  "Domains Offered (comma separated)": "उपलब्ध डोमेन (अल्पविराम से अलग)",
  "Domains": "डोमेन",
  "Government Department": "सरकारी विभाग",
  "Officer / Representative Name": "अधिकारी / प्रतिनिधि का नाम",
  "Officer Name": "अधिकारी का नाम",
  "Company Name": "कंपनी का नाम",
  "Company Email": "कंपनी ईमेल",
  "Company": "कंपनी",
  "Industry / Domain": "उद्योग / डोमेन",
  "Full Name": "पूरा नाम",
  "Full Address": "पूरा पता",
  "Research Area": "शोध क्षेत्र",
  "Research area": "शोध क्षेत्र",
  "Authority ID": "प्राधिकरण आईडी",
  "Authority Id": "प्राधिकरण आईडी",
  "Employee ID": "कर्मचारी आईडी",
  "Employee Id": "कर्मचारी आईडी",
  "🎤 Speak Your Problem": "🎤 अपनी समस्या बोलें",
  "Speak Your Problem": "अपनी समस्या बोलें",
  "Speak your problem": "अपनी समस्या बोलें",
  "⏹ Stop Recording": "⏹ रिकॉर्डिंग रोकें",
  "Stop Recording": "रिकॉर्डिंग रोकें",
  "Listening… speak now, the description field will fill in automatically.": "सुन रहे हैं… बोलें, विवरण स्वतः भर जाएगा।",
  "Tap the button and speak — your words will appear in the description field below. You can edit the text afterwards.": "बटन दबाकर बोलें — आपके शब्द नीचे विवरण में दर्ज होंगे। आप बाद में संपादित कर सकते हैं।",
  "Government Problem": "सरकारी समस्या",
  "Industry Problem": "उद्योग समस्या",
  "Citizen Problem": "नागरिक समस्या",
  "LinkedIn": "लिंक्डइन",
  "University Problems": "विश्वविद्यालय समस्याएं",
  "All University Problems": "विश्वविद्यालय की सभी समस्याएं",
  "All Problems Allotted to University": "विश्वविद्यालय को आवंटित सभी समस्याएं",
  "No problems allocated to your university yet.": "आपके विश्वविद्यालय को अभी कोई समस्या आवंटित नहीं की गई है।",

  // Priorities & Statuses
  "HIGH (92%)": "उच्च (92%)",
  "MEDIUM (78%)": "मध्यम (78%)",
  "HIGH (88%)": "उच्च (88%)",
  "RESOLVED": "हल",
  "high": "उच्च",
  "medium": "मध्यम",
  "resolved": "हल",
  "new": "नया",
  "Completed": "पूर्ण",
  "Deployed": "लागू / तैनात",
  "Pilot": "पायलट परीक्षण",

  // Navigation labels
  "🔎 My Problems": "🔎 मेरी समस्याएं",
  "➕ Submit New Problem": "➕ नई समस्या दर्ज करें",
  "👤 Profile": "👤 प्रोफ़ाइल",
  "📁 My Projects": "📁 मेरे प्रोजेक्ट्स",
  "🏆 Leaderboard": "🏆 लीडरबोर्ड",
  "📁 University Projects": "📁 विश्वविद्यालय प्रोजेक्ट्स",
  "📊 Dashboard": "📊 डैशबोर्ड",
  "📥 Incoming Problems": "📥 प्राप्त समस्याएं",
  "📌 Allocations": "📌 आवंटन",
  "📋 Active Problems": "📋 सक्रिय समस्याएं",
  "👨‍🏫 Assigned Faculties": "👨‍🏫 आवंटित फैकल्टी",
  "👨‍🎓 Students Solving Problems": "👨‍🎓 समाधान कर रहे छात्र",
  "✅ Solved Problems": "✅ हल की गई समस्याएं",
  "🤝 Collaboration Proposals": "🤝 सहयोग प्रस्ताव",
  "🔗 Active Collaborations": "🔗 सक्रिय सहयोग",
  "📁 Past Projects": "📁 पूर्व परियोजनाएं",

  // Details
  "Area:": "क्षेत्र:",
  "Organization:": "संगठन:",
  "Solved Problem:": "हल की गई समस्या:",
  "Achievements:": "उपलब्धियां:",
  "Partners:": "भागीदार:",
  "🤝 Partners:": "🤝 भागीदार:",
  "~5.4 mo": "~5.4 माह",
  "⚡ SIH26043": "⚡ SIH26043",
  "⏳ Status:": "⏳ स्थिति:",
  "⏳ Uploading…": "⏳ अपलोड हो रहा है…",
  "✅ Reason validated": "✅ कारण सत्यापित",
  "✅ This solution works for my problem": "✅ यह समाधान मेरी समस्या के लिए काम करता है",
  "❌ This solution does not solve my problem": "❌ यह समाधान मेरी समस्या का समाधान नहीं करता",
  "🏢 Industry Involvement:": "🏢 उद्योग की भागीदारी:",
  "🏫 University:": "🏫 विश्वविद्यालय:",
  "👨‍🎓 Students Involved:": "👨‍🎓 शामिल छात्र:",
  "👨‍🏫 Allocated Faculty:": "👨‍🏫 आवंटित फैकल्टी:",
  "Faculty Mentoring:": "फैकल्टी मार्गदर्शन:",
  "Industry Name:": "उद्योग का नाम:",
  "Industry Partner:": "उद्योग भागीदार:",
  "Student Names Working on It:": "कार्यरत छात्र:",
  "Update Project Milestone": "प्रोजेक्ट माइलस्टोन अपडेट करें",
  "Current Milestone:": "वर्तमान माइलस्टोन:",
  "Select Next Milestone:": "अगला माइलस्टोन चुनें:",
  "Update Milestone": "माइलस्टोन अपडेट करें",
  "Student Interests": "छात्रों की रुचि / आवेदन",
  "Student Interests & Selection": "छात्र रुचि एवं टीम चयन",
  "Select for Team": "टीम के लिए चुनें",
  "Selected for Team": "टीम के लिए चयनित",
  "Confirm Team Selection": "टीम चयन की पुष्टि करें",
  "Already in Team": "पहले से टीम में शामिल",
  "Completed - Milestone Locked": "पूर्ण - माइलस्टोन लॉक है",
  "Only assigned faculty can update this project": "केवल आवंटित फैकल्टी ही इस प्रोजेक्ट को अपडेट कर सकते हैं",
  "No students have expressed interest yet.": "अभी तक किसी भी छात्र ने रुचि व्यक्त नहीं की है।",
  "No projects assigned to you yet.": "अभी तक आपको कोई प्रोजेक्ट आवंटित नहीं किया गया है।",
  "Citizen Submitted": "नागरिक द्वारा प्रस्तुत",
  "Government Submitted": "सरकार द्वारा प्रस्तुत",
  "Being Solved": "समाधानाधीन",
  "NEW REPORT": "नई रिपोर्ट",
  "Allotted": "आवंटित",
  "awaiting": "प्रतीक्षारत",
  "accepted": "स्वीकृत",
  "rejected": "अस्वीकृत",
  "Finalizing…": "अंतिम रूप दिया जा रहा है…",
  "remaining": "शेष",
  "Required Tech": "आवश्यक तकनीकें",
  "Suggested Industries": "सुझाए गए उद्योग",
  "Suggested Industry": "सुझाया गया उद्योग",
  "Interested Applicants": "इच्छुक आवेदक",
  "Smart Traffic Signal Automation": "स्मार्ट ट्रैफिक सिग्नल स्वचालन",
  "Solar Water Purifier Deployment": "सोलर वाटर प्यूरीफायर स्थापना",
  "40% Traffic Reduction": "ट्रैफिक में 40% की कमी",
  "12 Villages Benefited": "12 गांवों को लाभ",
  "Ranchi Municipal Corp": "राँची नगर निगम",
  "Jharkhand Rural Dev": "झारखंड ग्रामीण विकास",

  // Home Page - Top Government Bar
  "Government & Civic Services Portal": "सरकारी एवं नागरिक सेवा पोर्टल",
  "Accessibility": "सुगमता",
  "Help & Support": "सहायता और समर्थन",

  // Home Page - Navbar
  "Civic Problem Resolution Platform": "नागरिक समस्या समाधान मंच",
  "Home": "होम",
  "How It Works": "यह कैसे काम करता है",
  "Problems": "समस्याएं",
  "Ecosystem": "पारिस्थितिकी तंत्र",
  "Log In": "लॉग इन",
  "Select Language": "भाषा चुनें",

  // Home Page - Hero Section
  "Building Better Communities Together": "मिलकर बेहतर समुदाय का निर्माण",
  "Report a Problem.": "समस्या दर्ज करें।",
  "Find a Solution.": "समाधान खोजें।",
  "SamadhanSetu connects citizens, government, universities, students and industry to identify real civic problems and turn them into measurable solutions.": "समाधानसेतु नागरिकों, सरकार, विश्वविद्यालयों, छात्रों और उद्योग को वास्तविक नागरिक समस्याओं की पहचान करने और उन्हें मापने योग्य समाधानों में बदलने के लिए जोड़ता है।",
  "+ Report a Problem": "+ समस्या दर्ज करें",
  "Track a Problem": "समस्या ट्रैक करें",
  "✓ Multilingual Access": "✓ बहुभाषी पहुंच",
  "✓ Transparent Tracking": "✓ पारदर्शी ट्रैकिंग",
  "✓ Community Driven": "✓ समुदाय संचालित",

  // Home Page - Dashboard Overview Widget
  "Civic Issue Overview": "नागरिक समस्या अवलोकन",
  "● PLATFORM OVERVIEW": "● मंच अवलोकन",
  "Jharkhand • Civic Issues": "झारखंड • नागरिक समस्याएं",
  "Problems Reported": "दर्ज समस्याएं",
  "Resolved": "समाधानित",
  "Active Projects": "सक्रिय परियोजनाएं",

  // Home Page - Statistics Bar
  "Solutions Delivered": "समाधान प्रदत्त",
  "Institution Partners": "संस्थान भागीदार",
  "Districts Covered": "शामिल जिले",

  // Home Page - Problem Categories Section
  "Civic Problems": "नागरिक समस्याएं",
  "What would you like to report?": "आप क्या दर्ज करना चाहते हैं?",
  "Help identify problems around you. Your report can become the starting point for a real solution.": "अपने आस-पास की समस्याओं की पहचान करने में मदद करें। आपकी रिपोर्ट एक वास्तविक समाधान की शुरुआत बन सकती है।",
  "Roads & Transport": "सड़कें एवं परिवहन",
  "Damaged roads, traffic issues, street connectivity and public transport.": "क्षतिग्रस्त सड़कें, यातायात की समस्याएं, सड़क संपर्क और सार्वजनिक परिवहन।",
  "Water & Sanitation": "जल एवं स्वच्छता",
  "Water supply, drainage, sanitation and waste management concerns.": "जल आपूर्ति, जल निकासी, स्वच्छता और अपशिष्ट प्रबंधन संबंधी चिंताएं।",
  "Electricity": "बिजली",
  "Street lighting, power infrastructure and electricity-related civic issues.": "स्ट्रीट लाइट, बिजली का बुनियादी ढांचा और बिजली से जुड़े नागरिक मुद्दे।",
  "Public Services": "सार्वजनिक सेवाएं",
  "Problems related to public facilities, administration and civic services.": "सार्वजनिक सुविधाओं, प्रशासन और नागरिक सेवाओं से संबंधित समस्याएं।",

  // Home Page - How It Works Section
  "Simple Process": "सरल प्रक्रिया",
  "From Problem to Impact": "समस्या से प्रभाव तक",
  "SamadhanSetu creates a structured pathway from citizen-reported problems to innovative solutions.": "समाधानसेतु नागरिक द्वारा दर्ज समस्याओं से नवीन समाधानों तक एक संरचित मार्ग बनाता है।",
  "Report": "दर्ज करें",
  "Citizen submits a civic problem using text, image or voice.": "नागरिक पाठ, छवि या आवाज़ का उपयोग करके नागरिक समस्या दर्ज करते हैं।",
  "Validate": "सत्यापित करें",
  "AI-assisted validation checks quality, relevance and existing solutions.": "एआई-सहायता प्राप्त सत्यापन गुणवत्ता, प्रासंगिकता और मौजूदा समाधानों की जांच करता है।",
  "Connect": "जोड़ें",
  "Relevant universities and institutions receive suitable problem statements.": "संबंधित विश्वविद्यालयों और संस्थानों को उपयुक्त समस्या विवरण प्राप्त होते हैं।",
  "Innovate": "नवाचार करें",
  "Students and faculty develop practical solution proposals.": "छात्र और फैकल्टी व्यावहारिक समाधान प्रस्ताव विकसित करते हैं।",
  "Impact": "प्रभाव",
  "Industry and government help transform promising ideas into real outcomes.": "उद्योग और सरकार आशाजनक विचारों को वास्तविक परिणामों में बदलने में मदद करते हैं।",

  // Home Page - Connected Ecosystem Section
  "Connected Ecosystem": "जुड़ा हुआ पारिस्थितिकी तंत्र",
  "One Platform. Multiple Stakeholders.": "एक मंच। अनेक हितधारक।",
  "Bringing the right people together around real-world problems.": "वास्तविक दुनिया की समस्याओं के इर्द-गिर्द सही लोगों को एक साथ लाना।",
  "👤 Citizen": "👤 नागरिक",
  "🏛️ University": "🏛️ विश्वविद्यालय",
  "🎓 Student": "🎓 छात्र",
  "🏭 Industry": "🏭 उद्योग",
  "🏢 Government": "🏢 सरकार",
  "✓ Impact": "✓ प्रभाव",
  "Citizen → University → Student → Industry → Government → Impact": "नागरिक → विश्वविद्यालय → छात्र → उद्योग → सरकार → प्रभाव",

  // Home Page - Call to Action
  "Have a problem in your community?": "क्या आपके समुदाय में कोई समस्या है?",
  "Your observation could become someone's next solution.": "आपका अवलोकन किसी का अगला समाधान बन सकता है।",
  "Report a Problem →": "समस्या दर्ज करें →",

  // Home Page - Footer
  "A civic problem resolution platform connecting communities, institutions and innovators to create meaningful local impact.": "सार्थक स्थानीय प्रभाव पैदा करने के लिए समुदायों, संस्थानों और नवप्रवर्तकों को जोड़ने वाला एक नागरिक समस्या समाधान मंच।",
  "Platform": "मंच",
  "Report Problem": "समस्या दर्ज करें",
  "Stakeholders": "हितधारक",
  "Citizens": "नागरिक",
  "Universities": "विश्वविद्यालय",
  "Support": "समर्थन",
  "Help Centre": "सहायता केंद्र",
  "Privacy Policy": "गोपनीयता नीति",
  "Terms of Use": "उपयोग की शर्तें",
  "© 2026 SamadhanSetu. Civic Technology Initiative.": "© 2026 समाधानसेतु। नागरिक प्रौद्योगिकी पहल।",
  "Designed for citizen-centric problem solving.": "नागरिक-केंद्रित समस्या समाधान के लिए डिज़ाइन किया गया।",

  // Login / Signup Page - Left Panel
  "SECURE CIVIC ACCESS": "सुरक्षित नागरिक पहुंच",
  "One platform.": "एक मंच।",
  "Many possibilities.": "अनेक संभावनाएं।",
  "Access SamadhanSetu to report civic problems, track resolutions, collaborate on solutions and connect communities with institutions.": "नागरिक समस्याओं की रिपोर्ट करने, समाधान ट्रैक करने, समाधानों पर सहयोग करने और समुदायों को संस्थानों से जोड़ने के लिए समाधानसेतु का उपयोग करें।",
  "SamadhanSetu Ecosystem": "समाधानसेतु पारिस्थितिकी तंत्र",
  "Secure authentication": "सुरक्षित प्रमाणीकरण",
  "Role-based portal access": "भूमिका-आधारित पोर्टल पहुंच",
  "Multilingual civic platform": "बहुभाषी नागरिक मंच",
  "← Back to Home": "← होम पर वापस",

  // Login / Signup Page - Headings & Tabs
  "Welcome back": "वापसी पर स्वागत है",
  "Create your account": "अपना खाता बनाएं",
  "Sign in to access your SamadhanSetu portal.": "अपने समाधानसेतु पोर्टल तक पहुंचने के लिए साइन इन करें।",
  "Register to join the SamadhanSetu civic ecosystem.": "समाधानसेतु नागरिक पारिस्थितिकी तंत्र में शामिल होने के लिए पंजीकरण करें।",
  "Sign Up": "साइन अप",
  "Select Portal Role": "पोर्टल भूमिका चुनें",
  "Citizen": "नागरिक",
  "Government": "सरकार",
  "University": "विश्वविद्यालय",
  "Student": "छात्र",
  "Faculty": "फैकल्टी",
  "Industry": "उद्योग",

  // Login / Signup Page - Form Fields & Labels
  "Full Name": "पूरा नाम",
  "Enter your full name": "अपना पूरा नाम दर्ज करें",
  "Email Address": "ईमेल पता",
  "name@example.com": "name@example.com",
  "City *": "शहर *",
  "Select your city…": "अपना शहर चुनें…",
  "District": "ज़िला",
  "Select District": "ज़िला चुनें",
  "Authority ID *": "प्राधिकरण आईडी *",
  "Enter Authority ID": "प्राधिकरण आईडी दर्ज करें",
  "Government Department *": "सरकारी विभाग *",
  "Enter government department": "सरकारी विभाग दर्ज करें",
  "Designation *": "पदनाम *",
  "e.g. Deputy Commissioner": "उदा. उप-आयुक्त",
  "Select University *": "विश्वविद्यालय चुनें *",
  "Select University": "विश्वविद्यालय चुनें",
  "University Department *": "विश्वविद्यालय विभाग *",
  "e.g. Computer Engineering": "उदा. कंप्यूटर इंजीनियरिंग",
  "Student ID *": "छात्र आईडी *",
  "Enter Student ID": "छात्र आईडी दर्ज करें",
  "Domain *": "डोमेन *",
  "Select Domain": "डोमेन चुनें",
  "Primary Skill": "प्राथमिक कौशल",
  "e.g. Python, IoT, React": "उदा. पायथन, आईओटी, रिएक्ट",
  "LinkedIn Profile (Optional)": "लिंक्डइन प्रोफाइल (वैकल्पिक)",
  "Enter LinkedIn profile URL": "लिंक्डइन प्रोफाइल यूआरएल दर्ज करें",
  "GitHub Profile (Optional)": "गिटहब प्रोफाइल (वैकल्पिक)",
  "Enter GitHub ID / profile": "गिटहब आईडी / प्रोफाइल दर्ज करें",
  "Faculty ID *": "फैकल्टी आईडी *",
  "Enter Faculty ID": "फैकल्टी आईडी दर्ज करें",
  "Research Area *": "अनुसंधान क्षेत्र *",
  "Enter research area": "अनुसंधान क्षेत्र दर्ज करें",
  "Expertise *": "विशेषज्ञता *",
  "e.g. Machine Learning, Structural Eng.": "उदा. मशीन लर्निंग, स्ट्रक्चरल इंजीनियरिंग",
  "Select Company *": "कंपनी चुनें *",
  "Select Company": "कंपनी चुनें",
  "Official Company Email *": "आधिकारिक कंपनी ईमेल *",
  "Company Email *": "कंपनी ईमेल *",
  "Employee ID *": "कर्मचारी आईडी *",
  "Enter Employee ID": "कर्मचारी आईडी दर्ज करें",
  "Area of Expertise": "विशेषज्ञता का क्षेत्र",
  "Enter area of expertise": "विशेषज्ञता का क्षेत्र दर्ज करें",
  "Password": "पासवर्ड",
  "Enter your password": "अपना पासवर्ड दर्ज करें",
  "Hide": "छिपाएं",
  "Show": "दिखाएं",
  "Weak password": "कमज़ोर पासवर्ड",
  "Moderate password": "मध्यम पासवर्ड",
  "Strong password": "मजबूत पासवर्ड",
  "Confirm Password": "पासवर्ड की पुष्टि करें",
  "Re-enter password": "पासवर्ड पुनः दर्ज करें",
  "Remember me": "मुझे याद रखें",
  "Forgot password?": "पासवर्ड भूल गए?",
  "I agree to the": "मैं सहमत हूँ",
  "and": "और",
  "of SamadhanSetu.": "समाधानसेतु की।",
  "Continue to Portal →": "पोर्टल पर आगे बढ़ें →",
  "Create Account →": "खाता बनाएं →",
  "Please wait...": "कृपया प्रतीक्षा करें...",
  "CIVIC PLATFORM ACCESS": "नागरिक मंच पहुंच",
  "Official Civic Tech Initiative": "आधिकारिक नागरिक तकनीक पहल",
  "Reset Password": "पासवर्ड रीसेट करें",
  "Enter your registered email address to receive password reset instructions.": "पासवर्ड रीसेट निर्देश प्राप्त करने के लिए अपना पंजीकृत ईमेल पता दर्ज करें।",
  "Enter your registered email address and we'll send you a link to reset your password.": "अपना पंजीकृत ईमेल पता दर्ज करें और हम आपको अपना पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।",
  "Send Reset Link": "रीसेट लिंक भेजें",
  "Sending...": "भेजा जा रहा है...",
  "Role-based verification enforced by backend database.": "बैकएंड डेटाबेस द्वारा लागू भूमिका-आधारित सत्यापन।",
  "One platform.": "एक मंच।",
  "Many possibilities.": "अनेक संभावनाएं।",
  "Registered Email": "पंजीकृत ईमेल",
  "Select your city…": "अपना शहर चुनें…",
  "Select District": "ज़िला चुनें",
  "Select University": "विश्वविद्यालय चुनें",
  "Select Domain": "डोमेन चुनें",
  "Select Company": "कंपनी चुनें",
  "e.g. Computer Engineering": "उदा. कंप्यूटर इंजीनियरिंग",
  "e.g. React, Python, SQL": "उदा. रिएक्ट, पायथन, एसक्यूएल",
  "Enter LinkedIn ID / profile": "लिंक्डइन आईडी / प्रोफ़ाइल दर्ज करें",
  "Enter GitHub ID / profile": "गिटहब आईडी / प्रोफ़ाइल दर्ज करें",
  "Enter your full name": "अपना पूरा नाम दर्ज करें",
  "Enter Authority ID": "प्राधिकरण आईडी दर्ज करें",
  "Enter government department": "सरकारी विभाग दर्ज करें",
  "Enter designation": "पदनाम दर्ज करें",
  "Enter Student ID": "छात्र आईडी दर्ज करें",
  "Enter research area": "अनुसंधान क्षेत्र दर्ज करें",
  "Enter area of expertise": "विशेषज्ञता का क्षेत्र दर्ज करें",
  "Enter Employee ID": "कर्मचारी आईडी दर्ज करें",
  "Assigned University:": "आवंटित विश्वविद्यालय:",
  "Assigned Industry:": "आवंटित उद्योग:",
  "Assigned": "नियुक्त",
  "Formed": "गठित",
  "Pending Allocation": "आवंटन लंबित",
  "Pending Assignment": "सौंपना लंबित",
  "Solution Delivered": "समाधान प्रदान किया गया",

  // Login / Signup Page - Toasts & Validation
  "Please enter your email address.": "कृपया अपना ईमेल पता दर्ज करें।",
  "Please enter your password.": "कृपया अपना पासवर्ड दर्ज करें।",
  "Login successful": "लॉग इन सफल रहा",
  "Login failed": "लॉग इन विफल रहा",
  "Please select your city.": "कृपया अपना शहर चुनें।",
  "Passwords do not match.": "पासवर्ड मेल नहीं खाते।",
  "Please accept the Terms of Use and Privacy Policy.": "कृपया उपयोग की शर्तें और गोपनीयता नीति स्वीकार करें।",
  "Please fill in Authority ID, Department, and Designation.": "कृपया प्राधिकरण आईडी, विभाग और पदनाम भरें।",
  "Please select a University and enter Designation.": "कृपया विश्वविद्यालय चुनें और पदनाम दर्ज करें।",
  "Please fill in University, Department, Student ID, and Domain.": "कृपया विश्वविद्यालय, विभाग, छात्र आईडी और डोमेन भरें।",
  "Please fill in University, Faculty ID, Research Area, and Expertise.": "कृपया विश्वविद्यालय, फैकल्टी आईडी, अनुसंधान क्षेत्र और विशेषज्ञता भरें।",
  "Please fill in Company, Company Email, Employee ID, Designation, and Domain.": "कृपया कंपनी, कंपनी ईमेल, कर्मचारी आईडी, पदनाम और डोमेन भरें।",
  "Account created successfully.": "खाता सफलतापूर्वक बनाया गया।",
  "Account created successfully": "खाता सफलतापूर्वक बनाया गया",
  "Account created! Please check your email to confirm your registration.": "खाता बन गया! कृपया अपना पंजीकरण पुष्ट करने के लिए अपना ईमेल जांचें।",
  "Account created! Please check your email to verify your account before logging in.": "खाता बन गया! कृपया लॉग इन करने से पहले अपने खाते को सत्यापित करने के लिए अपना ईमेल जांचें।",
  "Password reset link sent! Check your inbox.": "पासवर्ड रीसेट लिंक भेजा गया! अपना इनबॉक्स जांचें।",
  "Failed to send reset link": "रीसेट लिंक भेजने में विफल",
  "Could not send reset link": "रीसेट लिंक नहीं भेजा जा सका",
  "Signup failed": "साइन अप विफल रहा",
};

export const englishToHindi = Object.keys(translations.en || {}).reduce((acc, key) => {
  const en = translations.en[key];
  const hi = translations.hi?.[key];
  if (typeof en === 'string' && typeof hi === 'string') acc[en] = hi;
  return acc;
}, { ...extraHi });

export function translateText(text, lang) {
  if (lang !== 'hi' || text == null) return text;
  if (typeof text !== 'string') return text;

  const trimmed = text.trim();
  if (englishToHindi[trimmed]) return englishToHindi[trimmed];
  if (englishToHindi[text]) return englishToHindi[text];

  // Dynamic pattern matches
  if (text.startsWith('Allocated to ')) {
    const target = text.slice('Allocated to '.length);
    return `${englishToHindi[target] || target} को आवंटित किया गया`;
  }
  if (text.startsWith('Your Priority Rank: #')) {
    return `आपकी प्राथमिकता रैंक: #${text.slice('Your Priority Rank: #'.length)}`;
  }
  if (text.includes('You Accepted This Problem')) {
    return 'आपने इस समस्या को स्वीकार किया';
  }
  if (text.includes('You Rejected This Problem')) {
    return 'आपने इस समस्या को अस्वीकार किया';
  }
  if (text.startsWith('Students Working: ')) {
    return `कार्यरत छात्र: ${text.slice('Students Working: '.length)}`;
  }
  if (text.startsWith('Interested Applicants (')) {
    const num = text.replace(/[^\d]/g, '');
    return `इच्छुक आवेदक (${num})`;
  }
  if (text.endsWith(' students')) {
    const num = text.replace(/[^\d]/g, '');
    return `${num} छात्र`;
  }
  if (text.startsWith('Total Submitted: ')) {
    return `कुल प्रस्तुत: ${text.slice('Total Submitted: '.length)}`;
  }
  if (text.startsWith('Proposal ') && text.endsWith('.')) {
    const action = text.slice('Proposal '.length, -1).toLowerCase();
    return action === 'accepted' ? 'प्रस्ताव स्वीकार कर लिया गया।' : 'प्रस्ताव अस्वीकार कर दिया गया।';
  }
  if (text.startsWith('This problem is selected by ') && text.includes('so you would not have to work on this')) {
    const uni = text.replace('This problem is selected by ', '').replace(/\.?\s*so you would not have to work on this\.?/i, '').trim();
    return `यह समस्या ${englishToHindi[uni] || uni} द्वारा चुनी गई है इसलिए आपको इस पर काम नहीं करना होगा।`;
  }
  if (text.includes('days remaining') || text.includes('day remaining')) {
    return text
      .replace(/(\d+)\s*days?\s*remaining/gi, '$1 दिन शेष')
      .replace(/(\d+)d\s*(\d+)h\s*remaining/gi, '$1 दिन $2 घंटे शेष')
      .replace(/(\d+)h\s*(\d+)m\s*remaining/gi, '$1 घंटे $2 मिनट शेष')
      .replace('for accepting/rejecting', 'स्वीकार/अस्वीकार करने के लिए');
  }

  return text;
}

export function useTranslate() {
  const { lang } = useLanguage();
  return (text) => translateText(text, lang);
}

export default function Trans({ text }) {
  const { lang } = useLanguage();
  return translateText(text, lang);
}
